stages:
  - build
  - test

default:
  # Cancel jobs if newer commits are pushed to the branch
  interruptible: true
  image: "registry.gitlab.com/gwastar/adlib"

workflow:
  rules:
    # run merge request pipelines
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # do not run branch pipelines if corresponding merge requests exist...
    # (this avoids duplicate pipelines)
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    # ...but otherwise run branch pipelines
    - if: $CI_COMMIT_BRANCH

.expensive-job:
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      allow_failure: false
    - when: manual
      allow_failure: true

.build-meson:
  stage: build
  artifacts:
    paths:
      - "${CI_PROJECT_DIR}/_${CI_JOB_NAME_SLUG}/tests"
    exclude:
      - "${CI_PROJECT_DIR}/_${CI_JOB_NAME_SLUG}/tests/*.p"
      - "${CI_PROJECT_DIR}/_${CI_JOB_NAME_SLUG}/tests/**/*.o"
    expire_in: 1 week
  script:
    - meson setup ${MESON_FLAGS} _${CI_JOB_NAME_SLUG}
    - meson compile -C _${CI_JOB_NAME_SLUG}

.use-clang:
  variables:
    CC: "clang"
    LD: "lld"

build-gcc-release:
  extends: .build-meson
  variables:
    MESON_FLAGS: "-Dbuildtype=release"

build-gcc-debug:
  extends:
    - .build-meson
    - .expensive-job
  variables:
    MESON_FLAGS: "-Dbuildtype=debug"

build-clang-release:
  extends:
    - .build-meson
    - .use-clang
    - .expensive-job
  variables:
    MESON_FLAGS: "-Dbuildtype=release"

build-asan-ubsan:
  extends:
    - .build-meson
    - .use-clang
    - .expensive-job
  variables:
    MESON_FLAGS: "-Dbuildtype=debugoptimized -Db_sanitize=address,undefined -Db_lundef=false"

build-msan:
  extends:
    - .build-meson
    - .use-clang
    - .expensive-job
  variables:
    MESON_FLAGS: "-Dbuildtype=debugoptimized -Db_sanitize=memory -Db_lundef=false"
  when: manual

.test:
  stage: test
  script:
    - "_${CI_JOB_NAME_SLUG/test/build}/tests/tests"

test-gcc-release:
  extends: .test
  needs: [build-gcc-release]

test-gcc-debug:
  extends:
    - .test
    - .expensive-job
  needs: [build-gcc-debug]

test-clang-release:
  extends:
    - .test
    - .expensive-job
  needs: [build-clang-release]

test-asan-ubsan:
  extends:
    - .test
    - .expensive-job
  needs: [build-asan-ubsan]

test-msan:
  extends:
    - .test
    - .expensive-job
  needs: [build-msan]
  when: manual